# Generated by Django 5.2.17 on 2026-09-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=150)),
            ],
        ),
    ]
