# Generated by Django 5.2.17 on 2026-09-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_n',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=150),
        ),
    ]
