# Generated by Django 5.2.17 on 2026-09-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client_date_n_alter_client_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(default='FR3563HD', max_length=11),
        ),
    ]
