# Generated by Django 5.2.17 on 2026-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_parcel_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
