# Generated by Django 5.2.17 on 2026-09-06 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_parcel_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
